Frontend Login
sfi-ru/KateheoDistr pull request #38
Opened 2016-10-07 16:31 UTC by zaveryukha

2016-10-07 16:38 UTC, dimaip requested changes
Молодец, но что-то какой-то мусор прокрался

2016-10-07 16:38 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Resources/Private/TypoScript/NodeTypes/LoginPage.ts2~
> +prototype(Sfi.Kateheo:LoginPage) {
Was ist das?

2016-10-07 16:38 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Resources/Private/TypoScript/NodeTypes/LoginPage.ts2~~
> +prototype(Sfi.Kateheo:LoginPage) {
Eh?

2016-10-07 16:38 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Resources/Private/Templates/Authentication/index.html
> +							<p>You're logged in as <strong>"{account.accountIdentifier}"</strong></p>
Усё не по нашенски....

2016-10-07 17:05 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Resources/Private/TypoScript/NodeTypes/LoginPage.ts2~
> +prototype(Sfi.Kateheo:LoginPage) {
Dies ist eine separate Login-Seite
Потому что у нас по умолчанию прилеплены к странице меню и новостная лента - они та мне нужны

2016-10-07 17:06 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Resources/Private/TypoScript/NodeTypes/LoginPage.ts2~~
> +prototype(Sfi.Kateheo:LoginPage) {
аааа, ты про расширение файлов?

2016-10-07 17:07 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Resources/Private/Templates/Authentication/index.html
> +							<p>You're logged in as <strong>"{account.accountIdentifier}"</strong></p>
Ja, сейчас переведу

2016-10-08 03:37 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Resources/Private/TypoScript/NodeTypes/LoginPage.ts2~~
> +prototype(Sfi.Kateheo:LoginPage) {
Да

2016-10-08 03:42 UTC, dimaip requested changes
Neos.Demo следы остались

2016-10-08 03:42 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +        privilegeTarget: Neos_Demo_RegistrationAccess
Почему Neos_Demo?

2016-10-08 03:42 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +# Security policy for the Neos.Demo package                 #
Почему Neos.Demo?

2016-10-08 03:42 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +    Neos_Demo_RegistrationAccess:
Тот же вопрос

2016-10-08 03:42 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Resources/Private/Templates/Authentication/index.html
> +								<div class="form-group">
И тут. Выглядит как копи-паст с демо сайта. Надо бы переработать как следует :)

2016-10-08 19:26 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Resources/Private/Templates/Authentication/index.html
> +								<div class="form-group">
Слушай, я понял в чем проблема.
На само деле показывается форма из файла ../Packages/Plugins/Flowpack.Neos.FrontendLogin/Resources/Private/Templates/Authentication/Index.html
сюда установился плугин.
А я-то правлю :
../Packages/Sites/Sfi.Kateheo/Resources/Private/Templates/Authentication/index.html

Можно ли править файл в каталоге плугина?

2016-10-09 04:54 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Resources/Private/Templates/Authentication/index.html
> +								<div class="form-group">
Just no. Но можно в typoscript  поменять путь шаблона, как минимум.

2016-10-09 21:52 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +    Sfi_Kateheo_FlickrAccess:
Flickr? У вас будет Flickr?

2016-10-10 06:28 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +    Sfi_Kateheo_FlickrAccess:
простите, поправил.
хотя это было изначально, насколько я помню

2016-10-10 07:09 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +    Sfi_Kateheo_FlickrAccess:
Но зачем тебе такая роль впринципе? Тебе нужен Flickr?

2016-10-10 07:09 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +    Sfi_Kateheo_FlickrAccess:
А, сори, увидел

2016-10-10 07:10 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +# Security policy for the Neos.Demo package                 #
Вопрос остается

2016-10-10 07:14 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +    Sfi_Kateheo_FlickrAccess:
Да, убрал. Вроде все поправлено?

2016-10-10 07:47 UTC, dimaip requested changes
Вот еще поревьювил. Мужайся, тебе предстоит много работы, просто копи-пастом тут не обойдешься к сожалению.

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +      matcher: method(Neos\Demo\Controller\RegistrationController->(index|newAccount|createAccount|createTemporaryAccount)Action())
А что это за RegistrationController?

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +      matcher: method(Neos\Demo\Controller\RegistrationController->(index|newAccount|createAccount|createTemporaryAccount)Action())
Простая логика, слов Demo не должно остаться нигде...

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Views.yaml
> +    templatePathAndFilename: 'resource://Acme.Sfi.kateheo/Private/Templates/Authenticate/index.html'
Что за Acme.Sfi.kateheo и как вообще это работает? И работает ли?

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Resources/Public/Legacy/icon/manifest.json
>  		{
Просто на будущее, жутко не удобно, что ты в один PR запихнул кучу совершенно лишних файлов, усложняет процесс ревью.

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +      # fee74676-c42f-89da-208e-1741a66525d4 is the node identifier of the "member-area" node, by default located at "/sites/neosdemo/member-area"
Поменяй этот коммент? Что за by default located at "/sites/neosdemo/..."? Или удали.

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Settings.yaml
> +        'Flowpack.Neos.FrontendLogin': TRUE
Это строка лишняя, эта штука есть итак тут https://github.com/Flowpack/Flowpack.Neos.FrontendLogin/blob/master/Configuration/Settings.yaml#L22

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Settings.yaml
> +          'Flowpack.Neos.FrontendLogin': ['NodeTypes/*']
А это зачем? Тоже там есть.

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Views.yaml
> +    templatePathAndFilename: 'resource://Acme.Sfi.kateheo/Private/Templates/Authenticate/index.html'
Прошу прощения, что это вообще за файл? Его надо удалить. Он должен быть в Configuration/Views.yaml.

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Resources/Private/Templates/Authentication/index.html
> +										<input name="__authentication[TYPO3][Flow][Security][Authentication][Token][UsernamePassword][username]" class="form-control" id="typo3-username" type="text" placeholder="имя пользователя"/
Что-то с отступами в этом файле не так.

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Settings.yaml
> +      authentication:
Брр вот это тоже все в FrontendLogin итак есть. Убери.

2016-10-10 07:47 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +      matcher: method(Neos\Demo\Controller\RegistrationController->(index|newAccount|createAccount|createTemporaryAccount)Action())
Почитай ридми https://github.com/Flowpack/Flowpack.Neos.FrontendLogin
"This package mainly serves for demonstration purpose. You should be fine using it in productive applications, but if you need any custom behavior/style it's probably the easiest to create your own login form plugin. It's just a few files."

Neos.FrontendLogin сам по себе почти ничего не делает. Изучи его код внимательно, там всего пару файлов.
Использовать его, или сделать тебе свой плагин уже не так важно. Можешь и его использовать, но важно тебе понимать, что и как он делает.
И еще, тебе самому придется делать регистрацию пользователей, на подобие того как это сделано на демо сайте, но уже нормально. Так что эту роль можешь смело удалить, она тебе не поможет.

2016-10-10 08:05 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Views.yaml
> +    templatePathAndFilename: 'resource://Acme.Sfi.kateheo/Private/Templates/Authenticate/index.html'
Да, что-то странное проскочило

2016-10-10 08:23 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Resources/Public/Legacy/icon/manifest.json
>  		{
это что-то зацепилось из-за того, что я постоянно меняю права доступа при старте докера. вчера вконец достало и я разобрался с проблемой.

2016-10-10 08:23 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Configuration/Settings.yaml
> +      authentication:
убрал

2016-10-10 08:23 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Configuration/Settings.yaml
> +        'Flowpack.Neos.FrontendLogin': TRUE
убрал тоже

2016-10-10 08:24 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Configuration/Settings.yaml
> +          'Flowpack.Neos.FrontendLogin': ['NodeTypes/*']
убрал

2016-10-10 08:24 UTC, zaveryukha commented on Packages/Sites/Sfi.Kateheo/Resources/Private/Templates/Authentication/index.html
> +										<input name="__authentication[TYPO3][Flow][Security][Authentication][Token][UsernamePassword][username]" class="form-control" id="typo3-username" type="text" placeholder="имя пользователя"/
отступы поправил

2016-10-10 08:55 UTC, dimaip requested changes
Еще немного, еще чуть-чуть

2016-10-10 08:55 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Policy.yaml
> +# Security policy for the Neos.Demo package                 #
Убери или обнови коммент

2016-10-10 08:55 UTC, dimaip commented on Packages/Sites/Sfi.Kateheo/Configuration/Settings.yaml
> +        'Flowpack.Neos.FrontendLogin': TRUE
Где убрал? Почему тогда я это тут вижу?

2016-10-10 09:40 UTC, dimaip approved these changes

2016-10-10 09:41 UTC, dimaip commented
Ура, у тебя много терпения, теперь выглядит гораздо аккуратнее.

2016-10-10 09:43 UTC, merged